"""Update taxonomy table structure to match real columns

Revision ID: 38f381c32711
Revises: 
Create Date: 2025-08-25 16:36:24.146485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f381c32711'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taxonomies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asv', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('taxonomy', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taxonomies', schema=None) as batch_op:
        batch_op.drop_column('taxonomy')
        batch_op.drop_column('asv')

    # ### end Alembic commands ###
